import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";

// The release the wg-edge shell serves at /version.json. Baseline's deploy-worker.yml builds with
// WG_VERSION (the tag without its v) and WG_COMMIT (the tag commit); any other build is development.
export const DEVELOPMENT_VERSION = "0.0.0-dev";
export const WORKER_ENTRY_RELATIVE = "build/worker.mjs";

const SEMANTIC_VERSION = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/;
const FULL_COMMIT = /^[0-9a-f]{40}$/;
const NO_COMMIT = "0".repeat(40);

function headCommit(cwd) {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

export function resolveWorkerRelease({ cwd = process.cwd(), env = process.env } = {}) {
  const version = env.WG_VERSION ?? "";
  const commit = env.WG_COMMIT ?? "";
  const head = headCommit(cwd);

  if (!version && !commit) {
    return { version: DEVELOPMENT_VERSION, commit: FULL_COMMIT.test(head) ? head : NO_COMMIT };
  }
  if (!version || !commit) throw new Error("WG_VERSION and WG_COMMIT must be set together");
  if (!SEMANTIC_VERSION.test(version)) throw new Error(`WG_VERSION must be an exact semantic version X.Y.Z; received ${JSON.stringify(version)}`);
  if (!FULL_COMMIT.test(commit)) throw new Error("WG_COMMIT must be a full 40-character commit");

  const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf8"));
  if (pkg.version !== version) throw new Error(`WG_VERSION ${version} does not match package.json version ${pkg.version}`);
  if (head !== commit) throw new Error("WG_COMMIT must be the checked-out commit");
  return { version, commit };
}

export function renderWorkerEntry(release) {
  return [
    "// Generated by scripts/build.mjs. Do not edit; the release comes from WG_VERSION and WG_COMMIT.",
    'import { createSiteWorker } from "../src/worker/index.ts";',
    "",
    `export default createSiteWorker(${JSON.stringify(release)});`,
    ""
  ].join("\n");
}

export async function writeWorkerEntry({ cwd = process.cwd(), env = process.env } = {}) {
  const release = resolveWorkerRelease({ cwd, env });
  const target = join(cwd, WORKER_ENTRY_RELATIVE);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, renderWorkerEntry(release));
  return release;
}
